language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t kardevroop/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kardevroop/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-243037095679"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_ACCESS_KEY_VALUE"